"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import SiteNav from "./SiteNav";

type Page = "about" | "gallery" | "contact";
const image = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=85";
const gallery = ["https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1200&q=85", image];

export default function InnerPage({ type }: { type: Page }) {
  const pageContent = type === "about" ? <About /> : type === "gallery" ? <Gallery /> : <Contact />;
  return <div className="inner-page"><SiteNav /><main>{pageContent}</main><footer className="site-footer"><Link className="monogram" href="/">B<span>✦</span>G</Link><p>© 2026 Brahmastra Gym — Dehradun</p><Link href="/">Back home ↑</Link></footer></div>;
}

const Fade = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <motion.div className={className} initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease: [.2, .7, 0, 1] }}>{children}</motion.div>;
function About() { return <><section className="inner-hero"><div className="inner-hero__bg" /><Fade><p className="kicker">01 — Our approach</p><h1>THE WORK<br />IS <em>SACRED.</em></h1></Fade></section><section className="about-page"><Fade className="about-page__intro"><p className="kicker">More than training</p><h2>YOUR DAILY<br /><em>ADVANTAGE.</em></h2><p>At Brahmastra, strength is a practice. We created a place for Dehradun&apos;s most driven people to show up, switch off the noise, and do exceptional work.</p></Fade><div className="about-page__image"><Image src={image} alt="Brahmastra training space" fill sizes="(max-width: 800px) 100vw, 45vw" /></div><div className="values">{[["01", "A considered floor", "Every zone flows, so every minute has purpose."], ["02", "Quality without noise", "Exceptional equipment. An atmosphere with restraint."], ["03", "A culture of effort", "Come to improve — not to perform for the room."]].map(([number, title, copy]) => <Fade key={number} className="value"><span>{number}</span><i>✦</i><h3>{title}</h3><p>{copy}</p></Fade>)}</div></section></> }
function Gallery() { return <><section className="inner-hero inner-hero--gallery"><Fade><p className="kicker">02 — The club in motion</p><h1>BUILT TO<br /><em>BE FELT.</em></h1></Fade></section><section className="gallery-page"><div className="gallery-page__top"><p>Strength has a texture. Step inside the spaces that hold the work.</p><span>Dehradun / Uttarakhand / India</span></div><div className="masonry">{gallery.map((src, i) => <motion.figure key={src} className={`masonry__item masonry__item--${i + 1}`} initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .7, delay: i * .06 }}><Image src={src} alt={`Brahmastra Gym gallery image ${i + 1}`} fill sizes="(max-width: 700px) 100vw, (max-width: 1100px) 50vw, 33vw" /><figcaption>0{i + 1} <span>↗</span></figcaption></motion.figure>)}</div></section></> }
function Contact() { return <><section className="inner-hero inner-hero--contact"><Fade><p className="kicker">03 — A beginning</p><h1>FIND YOUR<br /><em>FIRE.</em></h1></Fade></section><section className="contact-page"><div className="map-card"><div className="map-card__contours" /><span>✦</span><p>BRAHMASTRA GYM<br />DEHRADUN</p></div><Fade className="contact-page__copy"><p className="kicker">The club is calling</p><h2>COME SEE<br />WHAT&apos;S <em>POSSIBLE.</em></h2><a className="button button--gold" href="mailto:hello@brahmastragym.com">Book a visit <i>↗</i></a><div className="contact-list"><a href="tel:+919876543210"><span>Phone</span>+91 98765 43210</a><a href="mailto:hello@brahmastragym.com"><span>Email</span>hello@brahmastragym.com</a><p><span>Location</span>Dehradun, Uttarakhand, India</p></div></Fade></section></> }
